apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- replicas.yaml
- config.properties

bases:
- ../../base

patches:
- replicas.yaml

configMapGenerator:
- name: mykustom-map
  files:
    - config.properties
